<?php
/*
 *
 * $Id$
 *
 * Software License Agreement (BSD License)
 *
 * Copyright (c) 2009, University of Portsmouth
 * All rights reserved.
 *
 * Redistribution and use of this software in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *   Redistributions of source code must retain the above
 *   copyright notice, this list of conditions and the
 *   following disclaimer.
 *
 *   Redistributions in binary form must reproduce the above
 *   copyright notice, this list of conditions and the
 *   following disclaimer in the documentation and/or other
 *   materials provided with the distribution.
 *
 *   Neither the name of University of Portsmouth nor the names of its
 *   contributors may be used to endorse or promote products
 *   derived from this software without specific prior
 *   written permission of University of Portsmouth
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
 * TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
?>
<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle(); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/screen.css', 'screen, projection'); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/print.css', 'print'); ?>
        <?php $this->headLink()->appendStylesheet('/css/blueprint/ie.css', 'screen, projection', 'lt IE 8'); ?>
        <?php $this->headLink()->appendStylesheet('/css/main.css', 'screen, projection'); ?>
        <?php echo $this->headLink(); ?>
        <?php if(isset($this->openIdServer)): ?>
        <link rel="openid.server" href="<?php echo $this->openIdServer; ?>" />
        <?php endif; ?>
    </head>
    <body>
        <div id="container" class="container">
            <div id="header" class="span-20">
                <h1><a href="/">OpenID Provider</a></h1>
            </div>
            <div id="navigation" class="span-4 last">
                <ul>
                    <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
                    <li><a href="/user/logout">Logout</a></li>
                    <?php else: ?>
                    <li><a href="/user/login">Login</a></li>
                    <li><a href="/user/register">Register</a></li>
                    <?php endif; ?>
                </ul>
            </div>
            <div id="content" class="span-24 last">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </body>
</html>